include: package:lint/analysis_options_package.yaml

analyzer:
  exclude: answer_sheet_auditor_frontend/lib/generated_plugin_registrant.dart

linter:
  rules:
    #Disabled use key in widget constructors
    use_key_in_widget_constructors: false
    sort_constructors_first: true
    prefer_double_quotes: false
    public_member_api_docs: false
    prefer_single_quotes: true
    always_specify_types: false
    sort_pub_dependencies: false
    constant_identifier_names: false
    overridden_fields: false
    avoid_unnecessary_containers: false
    annotate_overrides : false


