name: answer_sheet_auditor
description: A new Flutter application.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_auth: ^0.20.1
  firebase_core: ^0.7.0
  google_fonts: ^1.1.2
  dartz: ^0.9.2
  equatable: ^1.2.6
  provider: ^4.3.3
  shared_preferences: ^0.5.12+4
  intl: ^0.16.1
  fluttertoast: ^7.1.8
  lottie: ^0.7.0+1
  flutter_svg: ^0.20.0-nullsafety.3
  dio: ^3.0.10
  connectivity: ^2.0.2
  shimmer: ^1.1.2
  url_launcher: ^5.7.10
  get_it: ^5.0.6
  overlay_support: ^1.2.0-nullsafety.0
  flash: ^1.3.2
  data_connection_checker: ^0.3.4
  cupertino_icons: ^1.0.2
  firebase_storage: ^7.0.0
  uuid: 2.2.2
  file_picker: ^2.1.6
  firebase_ml_vision: ^0.10.0
  path_provider: ^1.6.27


dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.0.0



flutter:


  uses-material-design: true


  assets:
    - assets/
    - assets/icons/
    - assets/illustrations/

