name: Build Mobile Apps
on:
  push:
    branches:
      - main

jobs:
#  build_ios:
#    name: Build Flutter (iOS)
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: "12.x"
#      - uses: subosito/flutter-action@v1
#        with:
#          channel: "beta"
#      - run: flutter clean
#      - run: flutter pub get
#
#      - run: flutter build ios --release --no-codesign
#
#  build_appbundle:
#    name: Build AppBundle (Android)
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/setup-java@v1
#        with:
#          java-version: "12.x"
#      - uses: subosito/flutter-action@v1
#        with:
#          channel: "beta"
#
#      - run: flutter clean
#      - run: flutter pub get
#
#      - run: flutter build appbundle

  build_and_upload_apk:
    name: Build Apk (Android)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          channel: 'beta'

      # Step 2: Decode Google services configuration file
      - name: Decode google-services.json
        env:
          FIREBASE_CONFIG: ${{ secrets.FIREBASE_CONFIG }}
        run: echo $FIREBASE_CONFIG > android/app/google-services.json

      - run: flutter clean
      - run: flutter pub get
      - run: flutter build apk

      - uses: actions/upload-artifact@v1
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk